main: com.gmail.jamesbehan198.servermanager.ServerManager
name: ServerManager
version: 1.0.0
description: A massive server manager, with all your server needs :)

commands:
   setspawn:
      description: Set's the spawn.
      usage: /<command>
      
   spawn:
      description: Teleports you to spawn.
      usage: /<command>
   
   remspawn:
      description: Removes the current spawn.
      usage: /<command>
      
   admin:
      description: Admin mode base command!
      usage: /<command>
      
   walkspeed:
      description: Allows users to change their walk speed!
      aliases: [ws]
      usage: /<command>
      
   flyspeed:
      description: Allows users to change their fly speed!
      aliases: [fs]
      usage: /<command>
      
permissions:
   sm.admin.all:
      default: op
      children:
         sm.spam.caps.bypass: true
         sm.spam.ad.bypass: true
         sm.spam.chattimer.bypass: true
         sm.alts.bypass: true
         sm.jack.showhelp: true
         sm.jack.kick: true
         sm.adminmode: true
         sm.fun.player.walkspeed: true
         sm.fun.admin.flyspeed: true   
         
   sm.spam.caps.bypass:
      default: op
      
   sm.spam.ad.bypass:
      default: op
      
   sm.spam.chattimer.bypass:
      default: op
      
   sm.alts.bypass:
      default: op
      
   sm.jack.showhelp:
      default: op
      
   sm.jack.kick:
      default: op
      
   sm.adminmode:
      default: op
      
   sm.fun.player.walkspeed:
      default: op
      
   sm.fun.admin.flyspeed:
      default: op